export const jobCategoryMap: Record<string, string> = {
  '고급 운전 관련직': 'advanced_driving',
  '공학 기술직': 'engineering_tech',
  '공학 전문직': 'engineering_pro',
  '교육관련 서비스직': 'education_service',
  '금융 및 경영 관련직': 'finance_business',
  '기능직': 'skilled_trades',
  '기타 게임,오락,스포츠 관련직': 'gaming_entertain_sports',
  '기타 특수 예술직': 'special_arts',
  '기획서비스직': 'management', // Remapped from planning_service
  '농생명산업 관련직': 'agro_bio',
  '디자인 관련직': 'design',
  '매니지먼트 관련직': 'management',
  '무용 관련직': 'dance',
  '미술 및 공예 관련직': 'fine_art_craft',
  '법률 및 사회활동 관련직': 'legal_social',
  '보건의료 관련 서비스직': 'healthcare_service',
  '사무 관련직': 'office_admin',
  '사회 서비스직': 'social_service',
  '악기 관련직': 'musical_instrument',
  '안전 관련직': 'social_service', // Remapped from safety_security to social_service (Safety -> Helping people)
  '언어 관련 전문직': 'humanities_social', // Remapped from language_pro
  '연기 관련직': 'special_arts', // Remapped from acting
  '영상 관련직': 'media_video',
  '영업관련 서비스직': 'sales_service',
  '예술기획 관련직': 'arts_planning',
  '운동 관련직': 'sports',
  '웹,게임,애니메이션 관련직': 'web_game_animation',
  '음악 관련직': 'music',
  '의료관련 전문직': 'medical_pro',
  '의복제조 관련직': 'apparel_making',
  '이공계 교육 관련직': 'stem_education',
  '이미용 관련직': 'beauty_care',
  '이학 전문직': 'science_pro',
  '인문 및 사회과학 관련직': 'humanities_social',
  '인문계 교육 관련직': 'humanities_education',
  '일반 서비스직': 'general_service',
  '일반운전 관련직': 'general_driving',
  '자연친화 관련직': 'nature_friendly',
  '작가 관련직': 'writing_author',
  '조리 관련직': 'skilled_trades', // Remapped from culinary
  '환경관련 전문직': 'environmental_pro',
  '회계 관련직': 'accounting',
  'IT관련전문직': 'it_pro',
};
